export const config = {
  apiBaseUrl: process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:3001",
  wsUrl: process.env.NEXT_PUBLIC_WS_URL ?? "ws://localhost:3001/ws",
  cognitoUserPoolId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_ID ?? "",
  cognitoUserPoolClientId: process.env.NEXT_PUBLIC_COGNITO_USER_POOL_CLIENT_ID ?? "",
  loadBalancerUrl: process.env.NEXT_PUBLIC_LOAD_BALANCER_URL ?? "",
  awsLoadBalancerUrl: process.env.NEXT_PUBLIC_AWS_LOAD_BALANCER_URL ?? "",
  gcpLoadBalancerUrl: process.env.NEXT_PUBLIC_GCP_LOAD_BALANCER_URL ?? "",
  gcpWebUrl: process.env.NEXT_PUBLIC_GCP_WEB_URL ?? "",
  grafanaDashboardUrl: process.env.NEXT_PUBLIC_GRAFANA_DASHBOARD_URL ?? "",
  prometheusUrl: process.env.NEXT_PUBLIC_PROMETHEUS_URL ?? "",
  proofPackUrl: process.env.NEXT_PUBLIC_PROOF_PACK_URL ?? "/proof-pack",
  demoOrgId: process.env.NEXT_PUBLIC_DEMO_ORG_ID ?? "org_demo_public",
  defaultWorkspaceName: process.env.NEXT_PUBLIC_DEFAULT_WORKSPACE_NAME ?? "My NetPulse Workspace",
  defaultEndpointName: process.env.NEXT_PUBLIC_DEFAULT_ENDPOINT_NAME ?? "Recruiter Drill Endpoint",
  defaultEndpointUrl: process.env.NEXT_PUBLIC_DEFAULT_ENDPOINT_URL ?? "https://example.com/health",
  testAlertEmail: process.env.NEXT_PUBLIC_TEST_ALERT_EMAIL ?? "",
  testSlackWebhookUrl: process.env.NEXT_PUBLIC_TEST_SLACK_WEBHOOK_URL ?? "",
  testWebhookUrl: process.env.NEXT_PUBLIC_TEST_WEBHOOK_URL ?? "",
  showTestingHints: (process.env.NEXT_PUBLIC_SHOW_TESTING_HINTS ?? "").toLowerCase() === "true"
};
