#!/usr/bin/env bash

set -euo pipefail

if ! command -v aws >/dev/null 2>&1; then
  echo "aws CLI is required" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required" >&2
  exit 1
fi

usage() {
  cat <<USAGE
Usage:
  $(basename "$0") --slack-url <https-url> --webhook-url <https-url> [options]

Options:
  --env <dev|staging|prod>          Environment (default: prod)
  --profile <aws-profile>           AWS profile (default: netpulse-root)
  --region <aws-region>             AWS region (default: us-east-1)
  --app-id <amplify-app-id>         Amplify app id (auto-detect if omitted)
  --branch <branch-name>            Amplify branch (default: main for prod, else env name)
  --drill-email <email>             Drill email address to persist in local env helper
  --drill-secret <value>            Drill webhook secret value to persist in local env helper
  --no-release                      Do not trigger Amplify release job
  --allow-non-premium               Skip premium verification failure gate
  -h, --help                        Show this help

Example:
  $(basename "$0") \
    --slack-url https://webhook.site/<your-paid-slack-token> \
    --webhook-url https://webhook.site/<your-paid-webhook-token> \
    --env prod --profile netpulse-root --drill-email you@example.com
USAGE
}

ENV_NAME="prod"
PROFILE="netpulse-root"
REGION="${AWS_REGION:-us-east-1}"
APP_ID=""
BRANCH=""
SLACK_URL=""
WEBHOOK_URL=""
DRILL_EMAIL="${DRILL_EMAIL_ADDRESS:-}"
DRILL_SECRET="${DRILL_WEBHOOK_SECRET_VALUE:-}"
AUTO_RELEASE="true"
ALLOW_NON_PREMIUM="false"

while [ $# -gt 0 ]; do
  case "$1" in
    --env)
      ENV_NAME="$2"
      shift 2
      ;;
    --profile)
      PROFILE="$2"
      shift 2
      ;;
    --region)
      REGION="$2"
      shift 2
      ;;
    --app-id)
      APP_ID="$2"
      shift 2
      ;;
    --branch)
      BRANCH="$2"
      shift 2
      ;;
    --slack-url)
      SLACK_URL="$2"
      shift 2
      ;;
    --webhook-url)
      WEBHOOK_URL="$2"
      shift 2
      ;;
    --drill-email)
      DRILL_EMAIL="$2"
      shift 2
      ;;
    --drill-secret)
      DRILL_SECRET="$2"
      shift 2
      ;;
    --no-release)
      AUTO_RELEASE="false"
      shift
      ;;
    --allow-non-premium)
      ALLOW_NON_PREMIUM="true"
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [ -z "$SLACK_URL" ] || [ -z "$WEBHOOK_URL" ]; then
  echo "--slack-url and --webhook-url are required" >&2
  usage
  exit 1
fi

if [[ ! "$SLACK_URL" =~ ^https:// ]]; then
  echo "Slack URL must use https://" >&2
  exit 1
fi
if [[ ! "$WEBHOOK_URL" =~ ^https:// ]]; then
  echo "Webhook URL must use https://" >&2
  exit 1
fi

if [ -z "$BRANCH" ]; then
  if [ "$ENV_NAME" = "prod" ]; then
    BRANCH="main"
  else
    BRANCH="$ENV_NAME"
  fi
fi

if [ -z "$APP_ID" ]; then
  APP_ID="$(aws amplify list-apps \
    --profile "$PROFILE" \
    --region "$REGION" \
    --query "apps[?contains(name, 'netpulse') || contains(name, 'NetPulse')].[appId] | [0][0]" \
    --output text)"

  if [ -z "$APP_ID" ] || [ "$APP_ID" = "None" ]; then
    echo "Could not auto-detect Amplify app id; pass --app-id explicitly." >&2
    exit 1
  fi
fi

extract_webhooksite_uuid() {
  local url="$1"
  if [[ "$url" =~ ^https://webhook\.site/([0-9a-fA-F-]{36})/?$ ]]; then
    echo "${BASH_REMATCH[1]}"
    return 0
  fi
  return 1
}

validate_webhooksite_premium() {
  local label="$1"
  local url="$2"
  local uuid

  if ! uuid="$(extract_webhooksite_uuid "$url")"; then
    echo "[$label] URL is not a raw webhook.site UUID URL. Skipping premium check."
    return 0
  fi

  local token_info
  token_info="$(curl -sS "https://webhook.site/token/$uuid")"
  if ! echo "$token_info" | jq -e . >/dev/null 2>&1; then
    echo "[$label] token metadata is not publicly readable (likely private/account-bound). Skipping premium check."
    return 0
  fi
  local premium
  local expires_at
  premium="$(echo "$token_info" | jq -r '.premium // false')"
  expires_at="$(echo "$token_info" | jq -r '.expires_at // "unknown"')"

  echo "[$label] webhook.site token premium=$premium expires_at=$expires_at"

  if [ "$premium" != "true" ] && [ "$ALLOW_NON_PREMIUM" != "true" ]; then
    echo "[$label] token is not premium. Use your paid account URL from webhook.site dashboard, or pass --allow-non-premium." >&2
    exit 1
  fi
}

validate_webhooksite_premium "SLACK" "$SLACK_URL"
validate_webhooksite_premium "WEBHOOK" "$WEBHOOK_URL"

mkdir -p artifacts/drills
DRILL_ENV_FILE="artifacts/drills/${ENV_NAME}-drill.env"
{
  echo "# Generated by scripts/apply-paid-webhooksite.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  if [ -n "$DRILL_EMAIL" ]; then
    echo "export DRILL_EMAIL_ADDRESS='$DRILL_EMAIL'"
  fi
  echo "export DRILL_SLACK_WEBHOOK_URL='$SLACK_URL'"
  echo "export DRILL_WEBHOOK_RECEIVER_URL='$WEBHOOK_URL'"
  if [ -n "$DRILL_SECRET" ]; then
    echo "export DRILL_WEBHOOK_SECRET_VALUE='$DRILL_SECRET'"
  fi
  echo "export DRILL_SKIP_EMAIL_SUBSCRIPTION_CHECK='false'"
} > "$DRILL_ENV_FILE"
echo "Wrote local drill helper: $DRILL_ENV_FILE"

CONFIGURE_ARGS=(
  --env "$ENV_NAME"
  --app-id "$APP_ID"
  --branch "$BRANCH"
  --profile "$PROFILE"
  --region "$REGION"
  --test-slack-webhook-url "$SLACK_URL"
  --test-webhook-url "$WEBHOOK_URL"
  --show-testing-hints true
)

if [ -n "$DRILL_EMAIL" ]; then
  CONFIGURE_ARGS+=(--test-alert-email "$DRILL_EMAIL")
fi

./scripts/configure-amplify-branch-env.sh "${CONFIGURE_ARGS[@]}"

if [ "$AUTO_RELEASE" = "false" ]; then
  echo "Skipped Amplify release job (--no-release)."
  exit 0
fi

JOB_ID="$(aws amplify start-job \
  --app-id "$APP_ID" \
  --branch-name "$BRANCH" \
  --job-type RELEASE \
  --profile "$PROFILE" \
  --region "$REGION" \
  --query "jobSummary.jobId" \
  --output text)"

echo "Started Amplify release job: $JOB_ID"

for i in $(seq 1 60); do
  STATUS="$(aws amplify get-job \
    --app-id "$APP_ID" \
    --branch-name "$BRANCH" \
    --job-id "$JOB_ID" \
    --profile "$PROFILE" \
    --region "$REGION" \
    --query "job.summary.status" \
    --output text)"

  echo "attempt=$i status=$STATUS"

  if [ "$STATUS" = "SUCCEED" ]; then
    echo "Amplify deploy succeeded."
    exit 0
  fi

  if [ "$STATUS" = "FAILED" ] || [ "$STATUS" = "CANCELLED" ]; then
    echo "Amplify deploy ended with status=$STATUS" >&2
    exit 1
  fi

  sleep 10
done

echo "Timed out waiting for Amplify release job $JOB_ID" >&2
exit 1
